name: Deploy VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            cd /home/ubuntu

            git pull origin master

            cd fitcorn-id/fitcorn-api

            npm install

            npm run build

            pm2 startOrReload ecosystem.config.js

            pm2 save